language: cpp

addons:
  apt:
    sources:
      - sourceline: 'ppa:canonical-qt5-edgers/ubuntu1204-qt5'
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
      - sourceline: 'ppa:george-edison55/precise-backports'
    packages:
      - cmake
      - g++-6
      - libboost-all-dev
      - qtbase5-dev

before_script:
  - mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=DEBUG -DCMAKE_C_COMPILER=gcc-6 -DCMAKE_CXX_COMPILER=g++-6

script:
  - make
  - ./libvacationdb/tests/vacationdb_tests

matrix:
  include:
    - os: linux
      dist: precise
    - os: linux
      dist: trusty
