language: cpp
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - g++-6

before_script:
  - CC=gcc-6 CXX=g++-6 mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=DEBUG

script:
  - cd build && make