language: cpp
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - g++-6
      - libboost-all-dev
      - qtbase5-dev

before_script:
  - mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=DEBUG -DCMAKE_C_COMPILER=gcc-6 -DCMAKE_CXX_COMPILER=g++-6

script:
  - cd build && make